#!/usr/bin/env -S uv run --quiet --with numpy --with pillow python
"""Generates the bundled demo album: two original pieces plus cover art.

The audio is synthesised here rather than sourced, so nothing in the app bundle
carries a third-party licence. The two pieces are written as one continuous
performance and split mid-phrase, which is what makes them a demonstration of
gapless playback rather than merely two files.

    scripts/gen-demo-audio.py        # writes MuonPlayer/App/Demo/
"""
import subprocess
import sys
import tempfile
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw

RATE = 44100
OUT = Path(__file__).resolve().parent.parent / "MuonPlayer" / "App" / "Demo"

ALBUM = "Muon Demo"
ARTIST = "MuonPlayer"
TITLES = ["Rise", "Fall"]


def note(freq, dur, amp=0.2, decay=3.5):
    """A plucked tone: odd harmonics, exponential decay, soft attack."""
    t = np.linspace(0, dur, int(RATE * dur), endpoint=False)
    wave = np.zeros_like(t)
    for h, weight in ((1, 1.0), (2, 0.28), (3, 0.14), (5, 0.05)):
        wave += weight * np.sin(2 * np.pi * freq * h * t)
    env = np.exp(-decay * t)
    attack = np.minimum(t / 0.008, 1.0)
    return amp * wave * env * attack


def midi(n):
    return 440.0 * 2 ** ((n - 69) / 12)


def render():
    """One continuous performance: an A-minor arpeggio figure over four chords."""
    # A minor, F major, C major, G major — two bars each, at 100 bpm.
    chords = [[57, 60, 64], [53, 57, 60], [48, 52, 55], [55, 59, 62]]
    beat = 60.0 / 100
    step = beat / 2
    total = len(chords) * 2 * 8 * step + 3.0
    buf = np.zeros(int(RATE * total))

    pos = 0.0
    for cycle in range(2):
        for chord in chords:
            figure = [0, 1, 2, 1, 2, 1, 0, 1]
            for i, degree in enumerate(figure):
                pitch = chord[degree] + (12 if cycle == 1 and i % 4 == 2 else 0)
                tone = note(midi(pitch), 2.4, amp=0.16)
                at = int(pos * RATE)
                buf[at:at + len(tone)] += tone
                pos += step
            bass = note(midi(chord[0] - 24), 3.0, amp=0.13, decay=1.6)
            at = int((pos - 8 * step) * RATE)
            buf[at:at + len(bass)] += bass

    buf /= np.max(np.abs(buf)) * 1.08
    return buf


def split(buf):
    """Cut mid-phrase, exactly on a sample, with no fade on either side."""
    cut = len(buf) // 2
    return buf[:cut], buf[cut:]


def write_flac(samples, path, index, cover):
    raw = (np.clip(samples, -1, 1) * 32767).astype("<i2").tobytes()
    cmd = [
        "ffmpeg", "-y", "-loglevel", "error",
        "-f", "s16le", "-ar", str(RATE), "-ac", "1", "-i", "pipe:0",
        "-i", str(cover), "-map", "0:a", "-map", "1:v", "-c:v", "copy",
        "-disposition:v", "attached_pic",
        "-metadata", f"title={TITLES[index]}",
        "-metadata", f"artist={ARTIST}",
        "-metadata", f"album={ALBUM}",
        "-metadata", f"album_artist={ARTIST}",
        "-metadata", f"track={index + 1}/2",
        "-metadata", "date=2026",
        "-metadata", "comment=Original demo content, generated by scripts/gen-demo-audio.py",
        "-c:a", "flac", "-compression_level", "8", str(path),
    ]
    subprocess.run(cmd, input=raw, check=True)


def cover_art(path):
    size = 1000
    img = Image.new("RGB", (size, size))
    px = img.load()
    for y in range(size):
        for x in range(size):
            d = ((x - size / 2) ** 2 + (y - size / 2) ** 2) ** 0.5 / (size / 1.4)
            px[x, y] = (int(18 + 30 * (1 - d)), int(22 + 60 * (1 - d)), int(34 + 120 * (1 - d)))

    draw = ImageDraw.Draw(img)
    cx = cy = size / 2
    draw.ellipse([cx - 90, cy - 90, cx + 90, cy + 90], fill=(226, 232, 245))
    draw.ellipse([cx - 34, cy - 34, cx + 34, cy + 34], fill=(28, 34, 52))
    for i, r in enumerate((150, 215, 280, 345)):
        fade = 220 - i * 42
        draw.arc([cx - r, cy - r, cx + r, cy + r], start=-52, end=52,
                 fill=(fade, fade, fade), width=13)
        draw.arc([cx - r, cy - r, cx + r, cy + r], start=128, end=232,
                 fill=(fade, fade, fade), width=13)
    img.save(path, "PNG")


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    # The art is embedded in each FLAC, so it stays out of OUT — anything left
    # there is copied into the app bundle as a loose resource.
    with tempfile.TemporaryDirectory() as tmp:
        cover = Path(tmp) / "cover.png"
        cover_art(cover)

        first, second = split(render())
        for i, part in enumerate((first, second)):
            path = OUT / f"{i + 1:02d} {TITLES[i]}.flac"
            write_flac(part, path, i, cover)
            print(f"wrote {path.name}  {path.stat().st_size / 1024:.0f} KB  "
                  f"{len(part) / RATE:.1f}s")


if __name__ == "__main__":
    sys.exit(main())
