#!/bin/bash
# Generates MuonPlayer/Secrets.swift from .env (gitignored) so credentials are
# available to the app at runtime without committing them.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
set -a; source "$ROOT/.env"; set +a

cat > "$ROOT/MuonPlayer/Secrets.swift" <<EOF
// AUTO-GENERATED by scripts/gen-secrets.sh from .env — do not edit, do not commit.
import Foundation

enum Secrets {
    static let lastFMApiKey = "${LAST_FM_API_KEY:-}"
    static let lastFMApiSecret = "${LAST_FM_API_SECRET:-}"
}
EOF
echo "wrote MuonPlayer/Secrets.swift"
